[package]
name = "zenith"
version = "1.0.0"
edition = "2021"
authors = ["cptdawn"]
description = "A sleek, animated Wayland status bar for Hyprland"
license = "MIT"
readme = "README.md"
keywords = ["wayland", "statusbar", "hyprland", "gtk4"]
categories = ["gui"]

[dependencies]
gtk4 = { version = "0.11.1", features = ["v4_12"] }
gtk4-layer-shell = "0.8.0"
glib = "0.22.3"
gdk4 = "0.11.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.0"
chrono = "0.4.44"
dirs = "6.0.0"
log = "0.4.29"
env_logger = "0.11.10"
anyhow = "1.0.102"
sysinfo = "0.38.4"
serde_json = "1.0.149"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
